FROM trudesk-preconfig:latest as config
COPY [".", "."]
RUN yarn build

FROM trudesk-preimage:latest
WORKDIR /usr/src/trudesk
COPY --from=config /usr/src/trudesk .
EXPOSE 8118

CMD [ "/bin/bash", "/usr/src/trudesk/startup.sh" ]


